In [1]:
#!pip install webdriver-manager

In [2]:
import selenium
from selenium import webdriver
import pandas as pd
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys

In [3]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException,ElementNotInteractableException,ElementClickInterceptedException

In [12]:
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(ChromeDriverManager().install())

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389

[WDM] - Driver [/Users/icg/.wdm/drivers/chromedriver/mac64/89.0.4389.23/chromedriver] found in cache

## Q 1.  scraping first 10 data analyst jobs in bangalore

In [13]:
driver.get("https://www.naukri.com")

search_job=driver.find_element_by_id("qsb-keyword-sugg")
search_job.send_keys("Data Analyst")
search_loc=driver.find_element_by_xpath("//input[@id='qsb-location-sugg']")
search_loc.send_keys("Bangalore")
search_button=driver.find_element_by_xpath("//div[@class='search-btn']/button")
search_button.click()

url=("https://www.naukri.com/data-analystdata-analyst-data-analyst-jobs-in-bangalore?k=data%20analystdata%20analyst%2C%20data%20analyst&l=bangalore%2C%20bangalore")
driver.get(url)

# extracting job-title, job-location, company_name, exp reqd
job_title=[]
job_loc=[]
company_name=[]
exp_reqd=[]

titles_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
for i in titles_tags:
    title=i.text
    job_title.append(title)
    
company_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
company_tags
for i in company_tags:
    company=i.text
    company_name.append(company) 
    
location_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]")
for i in location_tags:
    location=i.text
    job_loc.append(location)
    
exp_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']")
for i in exp_tags:
    exp=i.text
    exp_reqd.append(exp) 
    
print(len(company_name),len(job_title),len(job_loc),len(exp_reqd))
#import to dataframe
jobs=pd.DataFrame({})
jobs["Title"]=job_title[:10]
jobs["Company Name"]=company_name[:10]
jobs["Location"]=job_loc[:10]
jobs["Experience"]=exp_reqd[:10]
jobs

20 20 20 20

,Title,Company Name,Location,Experience
0,Senior Data Analyst,Cerner Corporation,Bangalore/Bengaluru,4-9 Yrs
1,Senior Data Analyst,Cerner,Bangalore/Bengaluru,3-5 Yrs
2,Data Analyst,WEIWO Communication Pvt. Ltd.,Bangalore/Bengaluru(Ulsoor),5-8 Yrs
3,Sr Manager I - Data Analyst (MINT),ExecBoardinAsia,Bangalore/Bengaluru,11-15 Yrs
4,Data Analyst,Myntra Designs Pvt. Ltd.,Bangalore/Bengaluru,3-6 Yrs
5,Sr Manager I Data Analyst (MINT),Walmart Labs,Bangalore/Bengaluru,10-15 Yrs
6,Data Analyst,CONDUENT BUSINESS SERVICES INDIA LLP,Bangalore/Bengaluru,1-2 Yrs
7,Data Analyst,GlaxoSmithKline Pharmaceuticals Limited,Bangalore/Bengaluru,2-7 Yrs
8,Junior Data Analyst,Happy Marketer Private Ltd,"Bangalore/Bengaluru, Mumbai (All Areas)",1-3 Yrs
9,Data Analyst,tech mahindra ltd,Bangalore/Bengaluru,4-8 Yrs

## Q 2. Scraping first 10 data scientist jobs in bangalore

In [33]:
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(ChromeDriverManager().install())

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389

[WDM] - Driver [/Users/icg/.wdm/drivers/chromedriver/mac64/89.0.4389.23/chromedriver] found in cache

In [34]:
# extracting job-title, job-location, company_name, description
driver.get("https://www.naukri.com")
search_job=driver.find_element_by_id("qsb-keyword-sugg")
search_job.send_keys("Data Scientist")
search_loc=driver.find_element_by_xpath("//input[@id='qsb-location-sugg']")
search_loc.send_keys("Bangalore")
search_button=driver.find_element_by_xpath("//div[@class='search-btn']/button")
search_button.click()

try:
    url=("https://www.naukri.com/data-scientist-jobs-in-bangalore?k=data%20scientist&l=bangalore")
    driver.get(url)
    time.sleep(3)
except NoSuchElementException as e:
    pass


job_title=[]
job_loc=[]
company_names=[]
fulldesc=[]

# extracting job-title, job-location, company_name, experience_required
titles_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
for i in titles_tags:
    title=i.text
    job_title.append(title)
    
company_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
for i in company_tags:
    company=i.text
    company_names.append(company)
    
location_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]")
for i in location_tags:
    location=i.text
    job_loc.append(location)
    
desc_tags=driver.find_elements_by_xpath("//div[@class='job-description fs12 grey-text']")
for i in desc_tags:
    desc=i.text
    fulldesc.append(desc)
    
print(len(job_title),len(company_names),len(job_loc),len(fulldesc))

#import to dataframe
job=pd.DataFrame({})
job["Title"]=job_title[:10]
job["Company Name"]=company_names[:10]
job["Location"]=job_loc[:10]
job["Description"]=fulldesc[:10]
job

20 20 20 20

,Title,Company Name,Location,Description
0,Data Scientist,CronJ IT Technologies Private Limited,Bangalore/Bengaluru,Flexibility in working independently and do ne...
1,Data Scientist - Machine Learning,AugmatrixGo,Bangalore/Bengaluru,BTech / MTech degree in from reputed institute...
2,Data Scientist - IBM Garage,IBM India Pvt. Limited,"Noida, Hyderabad/Secunderabad, Bangalore/Benga...",Required Technical and Professional ExpertiseP...
3,GAMMA Lead Data Scientist,Boston Consulting Group,"Mumbai, New Delhi, Chennai, Bangalore/Bengaluru",Practice Area Profile BCG GAMMA combines innov...
4,DBCG IND - GAMMA Senior Data Scientist,Boston Consulting Group,"Mumbai, New Delhi, Chennai, Bangalore/Bengaluru",What Youll Do We re looking for a passionate a...
5,Data Scientist/Senior Data Scientist,GANIT BUSINESS SOLUTIONS PRIVATE LIMITED,"Hyderabad/Secunderabad, Pune, Chennai, Bangalo...",Bachelors / Masters degree in Engineering / Te...
6,Senior Data Scientist | CES IT LTD | CMMI Level 5,CES Ltd.,"Kolkata, Mumbai, Hyderabad/Secunderabad, Pune,...",Logical and Analytical skills must be really s...
7,Data Scientist,Schneider Electric India Pvt. Ltd.,Bangalore/Bengaluru,In-depth understanding and modeling experience...
8,Associate Data Scientist - CRM & Loyalty,Shell India Markets Private Limited,Bangalore/Bengaluru,The RoleGeneral Position DefinitionThis role w...
9,Data Scientist - Business Analytics,Philips India Limited,Bangalore/Bengaluru,"Experience in the areas of analytics, exposure..."

In [35]:
driver.close()

In [4]:
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(ChromeDriverManager().install())

[WDM] - ====== WebDriver manager ======

[WDM] - Current google-chrome version is 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389
[WDM] - Trying to download new driver from https://chromedriver.storage.googleapis.com/89.0.4389.23/chromedriver_mac64.zip
[WDM] - Driver has been saved in cache [/Users/icg/.wdm/drivers/chromedriver/mac64/89.0.4389.23]

## Q3. Scraping 10 jobs using filter of location and Salary

In [5]:
#driver = webdriver.Chrome('./usr/local/bin/chromedriver.exe')
driver.get("https://www.naukri.com")
search_job=driver.find_element_by_id("qsb-keyword-sugg")
search_job.send_keys("Data Scientist")

search_button=driver.find_element_by_xpath("//div[@class='search-btn']/button")
search_button.click()
try:
    url=("https://www.naukri.com/data-scientist-jobs?k=data%20scientist")
    driver.get(url)
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='root']/div[3]/div[2]/section[1]/div[2]/div[2]/div[2]/div[2]/label/i").click()
    time.sleep(5)
    driver.find_element_by_xpath("//*[@id='root']/div[3]/div[2]/section[1]/div[2]/div[3]/div[2]/div[2]/label/i").click()
    
except NoSuchElementException as e:
    pass

# extracting job-title, job-location, company_name, exp reqd
title_name=[]
location=[]
Names=[]
experience=[]
try:
    time.sleep(2)
    tname_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
    for i in tname_tags:
        name=i.text
        title_name.append(name)
except NoSuchElementException as e:
    print("not found")
    
name_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
for i in name_tags:
    names=i.text
    Names.append(names)
    
loc_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]")
for i in loc_tags:
    loc=i.text
    location.append(loc)
    
experience_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']/span[1]")
for i in experience_tags:
    exp=i.text
    experience.append(exp) 
    
print(len(title_name),len(Names),len(location),len(experience))
#import to dataframe
d_job=pd.DataFrame({})
d_job["Title"]=title_name[:10]
d_job["Company Name"]=Names[:10]
d_job["Location"]=location[:10]
d_job["Experience"]=experience[:10]
d_job

20 20 20 20

,Title,Company Name,Location,Experience
0,Data Scientist - IBM Garage,IBM India Pvt. Limited,"Noida, Hyderabad/Secunderabad, Bangalore/Benga...",5-8 Yrs
1,Females Required- Data Scientist- Noida,Randstad,"Noida, Gurgaon/Gurugram, Delhi / NCR",3-7 Yrs
2,Data Scientist - Python & Machine Learning,FUTURES AND CAREERS,"Hyderabad/Secunderabad, Pune, Bangalore/Bengal...",2-7 Yrs
3,Data Scientist - Python & Machine Learning,FUTURES AND CAREERS,"Hyderabad/Secunderabad, Pune, Chennai, Bangalo...",2-7 Yrs
4,Only Fresher / Data Scientist / Data Analyst /...,GABA Consultancy services,"Noida, Gurgaon/Gurugram, Delhi / NCR",0-5 Yrs
5,Data Scientist - Hadoop/BigQuery,Jubna,Noida,3-6 Yrs
6,Data Scientist - Python / Machine Learning / T...,FUTURES AND CAREERS,"Mumbai, Hyderabad/Secunderabad, Bangalore/Beng...",3-8 Yrs
7,Data Scientist - Python & Machine Learning,FUTURES AND CAREERS,"Hyderabad/Secunderabad, Bangalore/Bengaluru, D...",2-7 Yrs
8,Required- Data Scientist (NLP)-Axis Bank - 6 m...,Axis Bank Limited,"Kolkata, New Delhi, Hyderabad/Secunderabad, Pu...",4-9 Yrs
9,Data Scientist - Python / Machine Learning / T...,FUTURES AND CAREERS,"Hyderabad/Secunderabad, Bangalore/Bengaluru, D...",3-8 Yrs

In [26]:
driver.close()

In [3]:
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(ChromeDriverManager().install())

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389

[WDM] - Driver [/Users/icg/.wdm/drivers/chromedriver/mac64/89.0.4389.23/chromedriver] found in cache

## Q4. Scraping first 10 jobs of data scientist in noida location

In [4]:
driver.get("https://www.glassdoor.co.in/index.htm")

try:
    search_job=driver.find_element_by_id("css-1etjok6")
    search_job.send_keys("Data Scientist")
    search_loc=driver.find_element_by_xpath("//input[@id='scLocation']")
    search_loc.send_keys("Noida")
    search_button=driver.find_element_by_xpath("//div[@class='ml-xsm col-4 p-0 headerSearchInput SearchStyles__searchBarLocationInput css-1ohf0ui']/button")
    search_button.click()
    
except NoSuchElementException:
    pass

url=("https://www.glassdoor.co.in/Job/noida-data-scientist-jobs-SRCH_IL.0,5_IC4477468_KO6,20.htm")
driver.get(url)

# scrape company_name, No. of days ago when job was posted, Rating of the company
company_name=[]
days_posted=[]
ratings=[]
time.sleep(2)
name_tags=driver.find_elements_by_xpath("//a[@class=' css-l2wjgv e1n63ojh0 jobLink']/span[1]")
for i in name_tags:
    name=i.text
    company_name.append(name)
    
days_tags=driver.find_elements_by_xpath("//div[@class='d-flex align-items-end pl-std css-mi55ob']")
for i in days_tags:
    days=i.text
    days_posted.append(days) 
    
try:
    rating_tags=driver.find_elements_by_xpath("//div[@class='d-flex flex-column css-x75kgh e1rrn5ka3']/span[1]")
    for i in rating_tags:
        rating=i.text
        ratings.append(rating)
        
except NoSuchElementException as e:
    ratings.append("No rating")

#import to dataframe
jobs=pd.DataFrame({})
jobs["Company Name"]=company_name[:10]
jobs["No. of days posted"]=days_posted[:10]
jobs["Ratings"]=ratings[:10]
jobs

                   Company Name No. of days posted Ratings
0                Biz2Credit Inc               30d+     3.8
1                           JLL                24h     4.0
2                         Adobe                 9d     4.4
3  Salasar New Age Technologies               30d+     5.0
4                      Techlive               30d+     5.0
5                       Asquero                11d     4.0
6                 Aedifico Tech               30d+     3.6
7               SearchUrCollege               30d+     5.0
8  Salasar New Age Technologies               30d+     3.0
9                       CRMNEXT                16d     3.8

In [13]:
driver.close()

### Q 5. Scrape data for first 10 companies. Scrape the Company name, Number of salaries, Average salary, Min salary, Max Salary.

In [35]:
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(ChromeDriverManager().install())

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389

[WDM] - Driver [/Users/icg/.wdm/drivers/chromedriver/mac64/89.0.4389.23/chromedriver] found in cache

In [36]:
driver.get("https://www.glassdoor.co.in/Salaries/index.htm")

try:
    search_job=driver.find_element_by_xpath("//input[@id='keyword']")
    search_job.send_keys("Data Scientist")
    search_loc=driver.find_element_by_xpath("//input[@id='loc']")
    search_loc.send_keys("Noida")
    search_button=driver.find_element_by_xpath("//div[@class='container-form']/button")
    search_button.click()
    
except NoSuchElementException:
    pass

# scrape Company name, Number of salaries, Average salary, Min salary, Max Salary.
company_name=[]
No_of_salaries=[]
Av_salary=[]
min_salary=[]
max_salary=[]

try:
    
    url=("https://www.glassdoor.co.in/Salaries/new-delhi-data-scientist-salary-SRCH_IL.0,9_IM1083_KO10,24.htm?clickSource=searchBtn")
    driver.get(url)
    
    try:        
        name_tags=driver.find_elements_by_xpath("//div[@data-test='job-info']/p[2]")
        for i in name_tags:
            name=i.text
            company_name.append(name)
    except NoSuchElementException as e:
        pass
    
    number_tags=driver.find_elements_by_xpath("//div[@data-test='job-info']/p[5]")
    for i in number_tags:
        number=i.text
        No_of_salaries.append(number)
        
    avSal_tags=driver.find_elements_by_xpath("//div[@class='col-2 d-none d-md-flex flex-row justify-content-end']/strong")
    for i in avSal_tags:
        avSal=i.text
        Av_salary.append(avSal)
       
    min_tags=driver.find_elements_by_xpath("//div[@class='common__RangeBarStyle__values d-flex justify-content-between ']")
    for i in min_tags:
        salary=i.text.split('\n')
        max_salary.append(salary[1])
        min_salary.append(salary[0])
        
except NoSuchElementException as e:
    pass

#print(len(company_name),len(No_of_salaries),len(Av_salary),len(min_salary),len(max_salary))
#import to dataframe
jobs=pd.DataFrame({})
jobs["Company Name"]=company_name[:10]
jobs["No. of salaries"]=No_of_salaries[:10]
jobs["Average Salary"]=Av_salary[:10]
jobs["Min. Salary"]=min_salary[:10]
jobs["Max. Salary"]=max_salary[:10]
jobs

,Company Name,No. of salaries,Average Salary,Min. Salary,Max. Salary
0,Tata Consultancy Services,14 salaries,"₹ 5,97,967",₹333K,"₹1,080K"
1,Accenture,14 salaries,"₹ 11,12,243",₹560K,"₹2,147K"
2,Delhivery,14 salaries,"₹ 12,12,741",₹436K,"₹11,274K"
3,IBM,13 salaries,"₹ 7,37,972",₹569K,"₹2,648K"
4,Ericsson-Worldwide,12 salaries,"₹ 7,15,984",₹350K,"₹1,565K"
5,UnitedHealth Group,10 salaries,"₹ 13,41,900","₹1,037K","₹1,500K"
6,Valiance Solutions,9 salaries,"₹ 7,90,812",₹487K,"₹1,421K"
7,Innovaccer,8 salaries,"₹ 11,81,047",₹602K,"₹1,644K"
8,ZS Associates,7 salaries,"₹ 9,89,924",₹196K,"₹1,755K"
9,EXL Service,7 salaries,"₹ 11,73,127",₹558K,"₹1,500K"

In [34]:
driver.close()

### Q 6. Scrape brand , Product Desc, Price , Discount of first 100 sunglasses listings on flipkart.com.

In [6]:
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(ChromeDriverManager().install())

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389

[WDM] - Driver [/Users/icg/.wdm/drivers/chromedriver/mac64/89.0.4389.23/chromedriver] found in cache

In [7]:
driver.get("https://www.flipkart.com/")

try:
    search_sunglasses=driver.find_element_by_xpath("//input[@class='_3704LK']")
    search_sunglasses.send_keys("sunglasses")   
    search_button=driver.find_element_by_xpath("//div[@class='_3OO5Xc']/button")
    search_button.click()
    
except NoSuchElementException:
    pass
# scrape brand , Product Desc, Price , Discount
brand_name=[]
Product_Desc=[]
Price=[]
Disc=[]

try:
    
    url=("https://www.flipkart.com/search?q=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off")
    driver.get(url)
except NoSuchElementException as e:
    pass

for i in range(0,3):
    name_tags=driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
    for i in name_tags:
        l=i.text
        brand_name.append(l)
    
    desc_tags=driver.find_elements_by_xpath("//a[@class='IRpwTa']")
    for i in desc_tags:
        desc=i.text
        Product_Desc.append(desc)
        
    price_tags=driver.find_elements_by_xpath("//div[@class='_30jeq3']")
    for i in price_tags:
        price=i.text
        Price.append(price)
        
    disc_tags=driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']/span[1]")
    for i in disc_tags:
        disc=i.text
        Disc.append(disc)
        
    # clicking next button to scrape data from 2nd and 3rd page    
    nxt_button=driver.find_element_by_xpath("//a[@class='_1LKTO3']/span[1]")
    if nxt_button.text=='Next':
        nxt_button.click()
        time.sleep(5)


sunglasses_df=pd.DataFrame({'Brand':brand_name[:100],
                         'Description':Product_Desc[:100],
                         'price':Price[:100],
                         'Discount':Disc[:100],
                         })
    
print(sunglasses_df)

           Brand                                        Description   price  \
0         Aislin    UV Protection, Gradient Cat-eye Sunglasses (58)  [₹459]
1      ROYAL SON             Polarized Retro Square Sunglasses (52)  [₹509]
2       Fastrack      UV Protection Wayfarer Sunglasses (Free Size)  [₹683]
3         PIRASO              UV Protection Aviator Sunglasses (54)  [₹187]
4       Fastrack   UV Protection Rectangular Sunglasses (Free Size)  [₹570]
..           ...                                                ...     ...
95      Fastrack       UV Protection Aviator Sunglasses (Free Size)  [₹592]
96    phenomenal  UV Protection, Mirrored Retro Square Sunglasse...  [₹399]
97  Singco India  UV Protection, Polarized Aviator Sunglasses (F...  [₹202]
98    phenomenal  UV Protection Retro Square Sunglasses (Free Size)  [₹399]
99        Aislin  UV Protection, Gradient Over-sized Sunglasses ...  [₹858]

   Discount
0   69% off
1   66% off
2   24% off
3   88% off
4   28% off
..      ...
95  34% off
96  80% off
97  71% off
98  80% off
99  79% off

[100 rows x 4 columns]

In [17]:
driver.close()

## Q 7. Scrape 100 rating,review summary,full review data from flipkart.com for iphone11 phone

In [52]:
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(ChromeDriverManager().install())

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389

[WDM] - Driver [/Users/icg/.wdm/drivers/chromedriver/mac64/89.0.4389.23/chromedriver] found in cache

In [9]:
# scrape rating , review, full review 
ratings=[]
review_summary=[]
full_review=[]
start_page=0
end_page=9

try:
    
    url=("https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace")
    driver.get(url)
    review_link=driver.find_element_by_xpath("//div[@class='_3UAT2v _16PBlm']")
    review_link.click()
    time.sleep(5)
except NoSuchElementException as e:
    pass

for i in range(start_page,end_page+1):
    rating_tags=driver.find_elements_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
    for i in rating_tags:
        rating=i.text
        ratings.append(rating)
    
    review_tags=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")
    for i in review_tags:
        review=i.text
        review_summary.append(review)
        
    full_tags=driver.find_elements_by_xpath("//div[@class='t-ZTKy']")
    for i in full_tags:
        fullreview=i.text
        full_review.append(fullreview)
        
    
    
        
    try:
        # clicking next button to scrape data for 100 records    
        nxt_button=driver.find_element_by_xpath("//nav[@class='yFHi8N']/span[1]")
        if nxt_button.text=='Next':
            nxt_button.click()
            time.sleep(5)
    except NoSuchElementException as e:
        pass

print(len(ratings),len(review_summary),len(full_review))
iphone_df=pd.DataFrame({'Ratings':ratings[:100],
                         'Review Summary':review_summary[:100],
                         'Full Review':full_review[:100]
                         })
    
print(iphone_df[70:99])

100 100 100
   Ratings      Review Summary  \
70       5           Brilliant
71       5    Perfect product!
72       5   Worth every penny
73       5       Great product
74       5  Highly recommended
75       5    Perfect product!
76       5           Fabulous!
77       5    Perfect product!
78       5           Wonderful
79       5   Worth every penny
80       5           Brilliant
81       5    Perfect product!
82       5   Worth every penny
83       5       Great product
84       5  Highly recommended
85       5    Perfect product!
86       5           Fabulous!
87       5    Perfect product!
88       5           Wonderful
89       5   Worth every penny
90       5           Brilliant
91       5    Perfect product!
92       5   Worth every penny
93       5       Great product
94       5  Highly recommended
95       5    Perfect product!
96       5           Fabulous!
97       5    Perfect product!
98       5           Wonderful

                                          Full Review
70  The Best Phone for the Money\n\nThe iPhone 11 ...
71  Amazing phone with great cameras and better ba...
72  Previously I was using one plus 3t it was a gr...
73  Amazing Powerful and Durable Gadget.\n\nI’m am...
74  iphone 11 is a very good phone to buy only if ...
75  It’s a must buy who is looking for an upgrade ...
76  This is my first iOS phone. I am very happy wi...
77  Value for money❤️❤️\nIts awesome mobile phone ...
78  *Review after 10 months of usage*\nDoesn't see...
79  Best budget Iphone till date ❤️ go for it guys...
80  The Best Phone for the Money\n\nThe iPhone 11 ...
81  Amazing phone with great cameras and better ba...
82  Previously I was using one plus 3t it was a gr...
83  Amazing Powerful and Durable Gadget.\n\nI’m am...
84  iphone 11 is a very good phone to buy only if ...
85  It’s a must buy who is looking for an upgrade ...
86  This is my first iOS phone. I am very happy wi...
87  Value for money❤️❤️\nIts awesome mobile phone ...
88  *Review after 10 months of usage*\nDoesn't see...
89  Best budget Iphone till date ❤️ go for it guys...
90  The Best Phone for the Money\n\nThe iPhone 11 ...
91  Amazing phone with great cameras and better ba...
92  Previously I was using one plus 3t it was a gr...
93  Amazing Powerful and Durable Gadget.\n\nI’m am...
94  iphone 11 is a very good phone to buy only if ...
95  It’s a must buy who is looking for an upgrade ...
96  This is my first iOS phone. I am very happy wi...
97  Value for money❤️❤️\nIts awesome mobile phone ...
98  *Review after 10 months of usage*\nDoesn't see...

In [55]:
driver.close()

## Q 8. Scrape data for first 100 sneakers from flipkart.com

In [59]:
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(ChromeDriverManager().install())

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389

[WDM] - Driver [/Users/icg/.wdm/drivers/chromedriver/mac64/89.0.4389.23/chromedriver] found in cache

In [61]:
driver.get("https://www.flipkart.com/")

try:
    search_sunglasses=driver.find_element_by_xpath("//input[@class='_3704LK']")
    search_sunglasses.send_keys("sneakers")   
    search_button=driver.find_element_by_xpath("//div[@class='_3OO5Xc']/button")
    search_button.click()
    
except NoSuchElementException:
    pass
# scrape brand , Product Desc, Price , Discount
brand_name=[]
Product_Desc=[]
Price=[]
Disc=[]

try:
    
    url=("https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off")
    driver.get(url)
except NoSuchElementException as e:
    pass

for i in range(0,3):
    name_tags=driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
    for i in name_tags:
        l=i.text
        brand_name.append(l)
    
    desc_tags=driver.find_elements_by_xpath("//a[@class='IRpwTa']")
    for i in desc_tags:
        desc=i.text
        Product_Desc.append(desc)
        
    price_tags=driver.find_elements_by_xpath("//div[@class='_30jeq3']")
    for i in price_tags:
        price=i.text
        Price.append(price)
        
    disc_tags=driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']/span[1]")
    for i in disc_tags:
        disc=i.text
        Disc.append(disc)
        
    # clicking next button to scrape data for 100 records    
    nxt_button=driver.find_element_by_xpath("//a[@class='_1LKTO3']/span[1]")
    if nxt_button.text=='Next':
        nxt_button.click()
        time.sleep(5)


sneakers_df=pd.DataFrame({'Brand':brand_name[:100],
                         'Description':Product_Desc[:100],
                         'price':Price[:100],
                         'Discount':Disc[:100],
                         })
    
print(sneakers_df)

                           Brand  \
0   ENJOY the celebration people
1                          Bucik
2                         Chevit
3                   Robbie jones
4                         Chevit
..                           ...
95                     ROCKFIELD
96                        Chevit
97                        Chevit
98                         Echor
99                     well feet

                                          Description price Discount
0                                    Sneakers For Men  ₹649  35% off
1   Multicolor Casual Shoes Mesh for Men Sneakers ...  ₹599  70% off
2   Perfect & Affordable Combo Pack of 02 Pairs Sn...  ₹499  72% off
3      Casual Sneakers Shoes For Men Sneakers For Men  ₹399  60% off
4   Combo Pack of 4 Casual Sneakers With Sneakers ...  ₹474  76% off
..                                                ...   ...      ...
95         Sneakers for men(black_6) Sneakers For Men  ₹396  67% off
96     Casual Sneakers Shoes For Men Sneakers For Men  ₹211  42% off
97                                   Sneakers For Men  ₹322  33% off
98                                   Sneakers For Men  ₹570  65% off
99  Rockstyle Trending Multicolor Ultralight canva...  ₹399  40% off

[100 rows x 4 columns]

In [62]:
driver.close()

## Q9. scrape 100 shoes which include “Brand” of the shoes , Short Shoe description, price

In [37]:
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(ChromeDriverManager().install())

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389

[WDM] - Driver [/Users/icg/.wdm/drivers/chromedriver/mac64/89.0.4389.23/chromedriver] found in cache

In [38]:

# scrape brand , short Desc, Price 
brand_name=[]
Product_Desc=[]
Price=[]


url=("https://www.myntra.com/shoes")
driver.get(url)

try:
    time.sleep(2)
    label_element = driver.find_element_by_xpath("//*[@id='mountRoot']/div/div[1]/main/div[3]/div[1]/section/div/div[6]/ul/li[1]/label/div")
    label_element.click()
    time.sleep(2)
    #TextValue  = label_element.text('Black')
    filter_button=driver.find_element_by_xpath("//*[@id='mountRoot']/div/div[1]/main/div[3]/div[1]/section/div/div[5]/ul/li[2]/label/div")
    filter_button.click()
    driver.refresh()  
except NoSuchElementException as e:
    pass

for i in range(0,2):
    name_tags=driver.find_elements_by_xpath("//h3[@class='product-brand']")
    #print(name_tags)
    for i in name_tags:
        l=i.text
        #print(l)
        brand_name.append(l)
    
    desc_tags=driver.find_elements_by_xpath("//h4[@class='product-product']")
    #print(desc_tags)
    for i in desc_tags:
        desc=i.text
        #print(desc)
        Product_Desc.append(desc)
    
        
    try:    
        price_tags=driver.find_elements_by_xpath("//div[@class='product-price']/span[1]")
        for i in price_tags[:100]:
            price=i.text
            Price.append(price[:9])
    except NoSuchElementException as e:
        pass
    # clicking next button to scrape data for 100 records    
    nxt_button=driver.find_element_by_xpath("//li[@class='pagination-next']/a")
    if nxt_button.text=='Next':
        nxt_button.click()
        time.sleep(5)
    
    

print(len(brand_name),len(Product_Desc),len(Price))
shoes_df=pd.DataFrame({'Brand':brand_name[:100],
                         'Description':Product_Desc[:100],
                         'price':Price[:100]
                         })
    
print(shoes_df)

100 100 100
        Brand                   Description      price
0        ALDO           Men Leather Loafers  Rs. 7799R
1        Nike    Men AIR ZOOM Running Shoes  Rs. 10121
2        Nike  Women AIR ZOOM Running Shoes  Rs. 7721R
3        Nike   Men JORDAN DELTA Basketball  Rs. 12495
4        Nike           Women Running Shoes  Rs. 7197R
..        ...                           ...        ...
95       Geox     Women Solid Leather Flats  Rs. 7492R
96  Cole Haan   Women Woven Design Sneakers  Rs. 7499R
97       Geox    Men Leather Formal Oxfords  Rs. 7867R
98       Geox    Men Leather Formal Oxfords  Rs. 9367R
99       Geox   Men Leather Formal Derbyacs  Rs. 11242

[100 rows x 3 columns]

In [39]:
driver.close()

## Q 10. scrape 3 attributes for each laptop: title , Ratings , Price from amazon.in

In [3]:
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(ChromeDriverManager().install())

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389

[WDM] - Driver [/Users/icg/.wdm/drivers/chromedriver/mac64/89.0.4389.23/chromedriver] found in cache

In [5]:

# scrape title , ratings, Price 
Title=[]
Ratings=[]
Price=[]


url=("https://www.amazon.in")
driver.get(url)

#locating the search bar
try:
    search_bar=driver.find_element_by_id("twotabsearchtextbox")
    search_bar.clear()
    search_bar.send_keys("laptops")   
    search_button=driver.find_element_by_id("nav-search-submit-button")
    search_button.click()
    
except NoSuchElementException:
    pass

#locating core i7 filter
filter_button=driver.find_elements_by_xpath("//a[@class='a-link-normal s-navigation-item']")
for i in filter_button:
    if i.text=='Intel Core i7':
        i.click()
        break
        
#locating core i7 filter
filter_button=driver.find_elements_by_xpath("//a[@class='a-link-normal s-navigation-item']")
for i in filter_button:
    if i.text=='Intel Core i9':
        i.click()
        break

#scraping titles
title=driver.find_elements_by_xpath("//span[@class='a-size-medium a-color-base a-text-normal']")
for i in title[:10]:
    Title.append(i.text)
    
#scraping price
price=driver.find_elements_by_xpath("//span[@class='a-price-whole']")
for i in price[:10]:
    Price.append(i.text)
    
#locating ratings
urls=driver.find_elements_by_xpath("//a[@class='a-link-normal a-text-normal']")
url=[]
for i in urls[:10]:
    url.append(i.get_attribute('href'))
for j in url:
    driver.get(j)
    try:
        rating=driver.find_element_by_xpath("//span[@id='acrCustomerReviewText']")
        rating.click()
        ratings=driver.find_element_by_xpath("//span[@class='a-size-medium a-color-base']")
        Ratings.append(ratings.text)
    except NoSuchElementException as e:
        Ratings.append("No ratings")
        
print(len(Title),len(Price),len(Ratings))
laptop_df=pd.DataFrame({'Title':Title[:10],
                         'Price':Price[:10],
                         'Ratings':Ratings[:10]
                         })
    
print(laptop_df)

10 10 10
                                               Title     Price       Ratings
0  ASUS VivoBook S S14 Intel Core i7-1165G7 11th ...    77,990  4.3 out of 5
1  HP Pavilion Gaming 10th Gen Intel Core i7 Proc...    83,077    No ratings
2  (Renewed) HP EliteBook 820 G4 Laptop (CORE I5 ...    40,790    No ratings
3  Lenovo Legion 5 10th Gen Intel Core i7 15.6 in...  5,22,077  4.3 out of 5
4  ASUS ROG G703GI-E5148T 17.3-inch FHD 144Hz/3ms...    90,990  3.9 out of 5
5  Dell Latitude 3410 14 Inch HD Intel Core i7 10...    39,990    No ratings
6  LifeDigital ZED AIR CX7 15.6 IPS FHD Screen Bl...    39,999  3.5 out of 5
7  (Renewed) DELL Latitude E6540 15.6-inch Laptop...    89,990    1 out of 5
8  Lenovo Legion Y530 Intel Core I7 8th Gen 15.6 ...    76,500  3.9 out of 5
9  HP 14 Thin & Light 14-inch FHD Laptop (11th Ge...    76,990  4.6 out of 5

In [6]:
driver.close()